name: Lint
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.run/**'
      - 'documentation/**'

  pull_request:
    types: [ opened, synchronize ]
    paths-ignore:
      - '.run/**'
      - 'documentation/**'
    branches:
      - main

  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: "Lint with golangci-lint"
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.62.0
          args: --timeout=3m